### PR TITLE
CJS Cleanup

### LINKED ISSUE #8: Unable to integrate with Nest.js [CommonJS support]
Guys, are you planning to add the CommonJS support?

### PR DESCRIPTION
**Pull request by arimgibson**
# PR Details
If moving forward with existing CJS implementation, these are some needed cleanup changes.

- Remove unused files package.cjs.json and package.esm.json
- Update package.json version to require Node 18+ (would recommend publishing as a 2.0.0 release as this is a breaking change)
- Updated README to mention Node 18+ is now required instead of recommended

## Other Rough Notes
This was a rough implementation of CJS in order to unblock our team. To reduce complexity in managing both module formats, I would recommend swapping to [tsup bundler](https://github.com/egoist/tsup) -- configless, leverages esbuild for faster bundles. A good read (recommending tsup) is Anthony Fu's (core team Vue, Vite) blog post [Ship ESM & CJS in one Package](https://antfu.me/posts/publish-esm-and-cjs).

The CJS migration performed also introduced another breaking change, see #13.

# Recommendations (Better Approach)
- Revert the previous CJS migration, as it includes a number of breaking changes not accounted for
  - Loses compatibility in Node versions prior to Node 18
  - Breaks type imports (see #13)
- Prepare for a 2.0.0 breaking change release with migration docs
  - Introduces CJS support
  - Removes dependencies on `node-fetch` and `formdata-node`
  - Adds type exports from root (see #13)
  - Fixes issues with SDK using FormData API request bodies
  - Closes #8 and #13

### CODE REVIEW

**Comment by arimgibson** [comment]
cc @pozorfluo lmk thoughts! I think the CJS migration was premature and shouldn't have been merged yet tbh as it introduces two breaking changes not accounted for. This would be my recommendation plan for moving forward.

**Comment by pozorfluo** [comment]
We'd like to move forward and drop node-fetch, formdata-node and fix the FormData issue.
We're ok with making node 18 required.


> Closes https://github.com/unipile/unipile-node-sdk/issues/8 and https://github.com/unipile/unipile-node-sdk/issues/13

I'm not sure I understand how this closes the Types export issue. Would you mind explaining it to me please ?

Thanks !

**Comment by arimgibson** [comment]
@pozorfluo okay sounds good! I was thinkin' we'd fix #13 in a v2.0.0 PR but if you're happy with the current CJS implementation, no worries. I will PR that as something separate and might play around with swapping the current building process for `tsup` as well for fun. Will keep you posted!

**Comment by arimgibson** [comment]
This PR should be merged in still then, and I'll add separate PRs for `tsup` and a fix for #13

**Comment by pozorfluo** [comment]
@arimgibson the PR has been automatically closed by deleting the head repository and can't seem to be reopened.

I will reproduce the content of the PR.

Thanks.

**Pull request closed without merging**
